### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by sunyclj** [ckkelvinchan/RealBasicVSR#11]
Hello,when will the train code be released？I hope to get the x2 pre-trained model through train.thanks.

**Comment by ckkelvinchan** [comment]
Hi @sunyclj, the training code is currently under review in MMEditing. It will be available by the end of this month. Please stay tuned!

**Comment by sunyclj** [comment]
@ckkelvinchan ok,thank u.

**Comment by Ha0Tang** [comment]
@ckkelvinchan Hi how about the code?

**Comment by ckkelvinchan** [comment]
Hello, the training code is actually on [MMEditing](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/real_basicvsr/realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds.py) now. But since the latest version of MMEditing is not released, we cannot use `mim install mmedit` and train directly. 

You can refer to MMEditing for the training for now. After the release of the latest version, I will update this repo, thanks for your patience and sorry for the delay.

**Comment by ckkelvinchan** [comment]
Hello @Ha0Tang @sunyclj, the training code has been added. Please try and let me know if there are any problems.

**Comment by sunyclj** [comment]
@ckkelvinchan thanks.when running 'mim train mmedit configs/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py --gpus 3 --launcher pytorch',  error occurred, AssertionError: Please install av to use video compression.what is av,please.

**Comment by ckkelvinchan** [comment]
Please use `pip install av` for installation. I will add it to README. Thanks for your reminder.

**Comment by sunyclj** [comment]
@ckkelvinchan I wanted to train an x2 model, would it work if I just changed scale = 2 in the realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py file?

**Comment by sunyclj** [comment]
@ckkelvinchan Yes.I modified some code and parameters,got x2 model.I have a question，in  folder basicvsr_net.py ，Why do you upsample LR image to get base and out + = base? thanks.
![1642123148409_F5D41874-1EC4-49c7-A070-6CE44576E63A](https://user-images.githubusercontent.com/44860428/149436283-6f9ee677-3528-408c-ade5-3d892ccf0b78.png)

**Comment by ckkelvinchan** [comment]
This is because we want to learn only the residue, since the input LR image should provide enough low-frequency information, and hence we do not need to learn it from scratch.

**Comment by zhixiongzuo** [comment]
Hi @sunyclj , how can you get x2 model? I comment upsample2 in basicvsr_net.py and change scale_factor to 2, but it didnot work.
