### ISSUE TITLE
Missing file (crop_sub_images.py).

### ISSUE THREAD

**Issue by sunlustar** [ckkelvinchan/RealBasicVSR#14]
Thanks for your great work, but it seems to lack a related file (crop_sub_images.py) in this project for training. Could you upload this file? I would appreciate it.

**Comment by ckkelvinchan** [comment]
Sorry about that. I just added it.

**Comment by sunlustar** [comment]
Thanks. But I have another problem when using distributed training. 

![image](https://user-images.githubusercontent.com/33677591/148668356-711db531-b30a-4625-b561-d32872c5e49c.png)

And I have checked my data path, it is
├─ REDS
├── train_sharp_sub
├───-000_s001
├───-000_s002

And when I use the single GPU training strategy, there is another problem like,
![image](https://user-images.githubusercontent.com/33677591/148668567-a4a155be-1eda-4506-b8cb-f2e097d84ad5.png)
It seems due to the dismatched batchsize dismension question between input and label, but I don't know why. The parameters in realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py keep same.

**Comment by ckkelvinchan** [comment]
If the training dataset path is correct, it seems that the validation set path is incorrect. Have you downloaded the UDM10 dataset for validation?

**Comment by sunlustar** [comment]
Yes, you are right, I got a mistake with the validation set path. However, it turned to the dismatched batchsize dismension question when using both distributed training and single GPU training,  have you ever meet this problem? Thanks.
![image](https://user-images.githubusercontent.com/33677591/148680803-850765b6-8587-4792-bc73-ad30fadeae1a.png)

**Comment by ckkelvinchan** [comment]
I did not encounter this error before. 

I have no access to the GPU server at the moment. I will run again when I get back the access later today. For now, you can try printing out the input and output dimensions to check if there are any problems.

**Comment by sunyclj** [comment]
@sunlustar Where was the UDM10 dataset downloaded? train_sharp_sub dataset is which of REDS? thanks. I don't find.
![1641885447930_6C7A586C-CFC5-4e1b-BDCF-883B5C106EA3](https://user-images.githubusercontent.com/44860428/148898126-5a4237a8-0a90-4c1c-8705-2548f789be12.png)

**Comment by sunlustar** [comment]
@sunyclj You can download udm10 dataset here, [https://www.terabox.com/web/share/link?surl=LMuQCVntRegfZSxn7s3hXw&path=%2Fproject%2Fpfnl](url)

**Comment by sunyclj** [comment]
thanks.but i don't have account.i don't download it from here.



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 11, 2022 15:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ckkelvinchan/RealBasicVSR] Missing file (crop_sub_images.py).(Issue #14)




 
@sunyclj You can download udm10 dataset here, https://www.terabox.com/web/share/link?surl=LMuQCVntRegfZSxn7s3hXw&amp;path=%2Fproject%2Fpfnl
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ha0Tang** [comment]
@ckkelvinchan @sunlustar  I also meet the error "ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work". How should I fix it?

**Comment by Ha0Tang** [comment]
And I have checked my data path, it is
├─ REDS
├── train_sharp_sub
├───-000_s001
├───-000_s002
├─ UDM10
├───-BIx4
├───---calendar
├───---city
├───---foliage
├───---walk
├───-GT
├───---calendar
├───---city
├───---foliage
├───---walk
├─ VideoLQ

am I missing something? @ckkelvinchan @sunlustar

**Comment by ckkelvinchan** [comment]
> And I have checked my data path, it is ├─ REDS ├── train_sharp_sub ├───-000_s001 ├───-000_s002 ├─ UDM10 ├───-BIx4 ├───---calendar ├───---city ├───---foliage ├───---walk ├───-GT ├───---calendar ├───---city ├───---foliage ├───---walk ├─ VideoLQ
> 
> am I missing something? @ckkelvinchan @sunlustar

It seems that the folder UDM10 is not downloaded correctly. You are using `Vid4`.
