### ISSUE TITLE
model size depends on image size?

### ISSUE THREAD

**Issue by jasony93** [ckkelvinchan/RealBasicVSR#25]
I have been trying to upscale 1920X1080 video.
It seems that my gpus can't load the model due to lack of capacity.
I am using 32GB V100 Tesla gpus.
When I tried it with smaller size video, it worked.

Is it right that higher gpu memory is required for bigger size videos?

And, would it be possible to upscale 1920X1080 video with my gpus?

**Comment by ckkelvinchan** [comment]
The model size is constant. It is just a larger image needs more memory to process. In practice, we could separate them into smaller patches and process. I will implement this functionality later.

**Comment by jasony93** [comment]
I appreciate your quick response.
