### ISSUE TITLE
  ERROR: Failed building wheel for mmcv-full

### ISSUE THREAD

**Issue by AK391** [ckkelvinchan/RealBasicVSR#29]
when using 

mim install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.10.0/index.html

I am looking to setup a space on huggingface spaces(https://huggingface.co/spaces) for this model at https://huggingface.co/spaces/akhaliq/RealBasicVSR

I was able to get the model working in colab but the space does not support cuda, is there a way around this thanks?

space code: https://huggingface.co/spaces/akhaliq/RealBasicVSR/blob/main/app.py#L4

**Comment by ckkelvinchan** [comment]
Hello, thank you for your efforts  to set up a space for RealBasicVSR. 

mim will automatically determine the appropriate version based on your pytorch and cuda version. Therefore I think simply `mim install mmcv-full` should be fine. Could you have a try and let me know if it works?

Thanks again.

**Comment by ckkelvinchan** [comment]
Oh my bad. Do you mean huggingface does not support cuda?

**Comment by AK391** [comment]
@ckkelvinchan Each Spaces environment is limited to 16GB RAM and 8 CPU cores
https://huggingface.co/docs/hub/spaces

**Comment by ckkelvinchan** [comment]
@AK391 `mmcv-full` can only be installed with CUDA. If CUDA is not available, you can use `mim install mmcv`. It lacks CUDA ops but it shouldn't affect RealBasicVSR. Please have a try.

**Comment by AK391** [comment]
@ckkelvinchan thanks, I tried that now getting

Traceback (most recent call last):
  File "inference_realbasicvsr.py", line 10, in <module>
    from mmedit.core import tensor2img
ModuleNotFoundError: No module named 'mmedit'

**Comment by ckkelvinchan** [comment]
@AK391 Thank you for your feedback. Please try the following:

1. pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.10/index.html
2. pip install mmedit

I tried and it works in colab. Please let me know if it still does not work.

<img width="371" alt="CleanShot 2022-03-12 at 08 23 07@2x" src="https://user-images.githubusercontent.com/7676947/157995110-dd99d9ac-4106-4459-9ea0-2cf3424206da.png">

**Comment by AK391** [comment]
@ckkelvinchan thanks it is working now, opened a PR here https://github.com/ckkelvinchan/RealBasicVSR/pull/30
