### ISSUE TITLE
Running the model on mobile

### ISSUE THREAD

**Issue by roimulia2** [ckkelvinchan/RealBasicVSR#33]
Hey there! 

Does the pre-trained model is suitable for mobile from a memory/CPU perspective? Or it's meant to be run on heavier machines. Thanks!

**Comment by ckkelvinchan** [comment]
I am afraid not. The current architecture of RealBasicVSR is not that lightweight (although it is more efficient than those larger ones.)

**Comment by hyygostudy** [comment]
Why I run with the 3090 still has the problem of CUDA out of memory

**Comment by ckkelvinchan** [comment]
> Why I run with the 3090 still has the problem of CUDA out of memory

It depends on the spatial resolution and the number of frames of your video. Could you provide me with more details?
