### ISSUE TITLE
I want a information about Colab Demo environment specification

### ISSUE THREAD

**Issue by ehanbin98** [ckkelvinchan/RealBasicVSR#34]
I want an information about Colab Demo environment specification.
I just know RAM and DISK capacity.
Can you notice the specification about Colab Goolge Compute Engine GPU ?(Name and any other information).

**Comment by ckkelvinchan** [comment]
Hi @ehanbin98, I think you can try `nvidia-smi` in colab.

**Comment by ehanbin98** [comment]
Thx :)
