### ISSUE TITLE
What should I do if I want to specify the output width and height?

### ISSUE THREAD

**Issue by cosperypf** [ckkelvinchan/RealBasicVSR#35]
I know "realbasicvsr_x4.py" can enlarge the picture 4 times, but it seems impossible to set a fixed width and height when I looked into "realbasicvsr_x4.py". So what should I do if I want to specify the output width and height? Thanks

**Comment by ckkelvinchan** [comment]
I think there are two ways to do it. 

1. You resize the input to 1/4 of the desired size, and then apply RealBasicVSR
2. You apply RealBasicVSR, and the resize it to the desired size.
