### ISSUE TITLE
loss for training

### ISSUE THREAD

**Issue by iSmida** [ckkelvinchan/RealBasicVSR#40]
Hi, thanks for your wonderful work. In the paper, you use cb loss, but in the codes, you use L1 loss in the config file. Which one is the right. Have you ever tried to modify the model for x1? Looking forward for your return. Thank you.

**Comment by ckkelvinchan** [comment]
Sorry about the confusion. Please follow the configuration file. 

About the 1x model, I haven't tried that. But note that this may be too computationally intensive, you may need to perform some downsampling operations.

**Comment by iSmida** [comment]
您的来信已收到，我会尽快处理

**Comment by iSmida** [comment]
您的来信已收到，我会尽快处理
