### ISSUE TITLE
Strange artifacts in results?

### ISSUE THREAD

**Issue by AIisCool** [ckkelvinchan/RealBasicVSR#41]
Not sure what the cause is.

Input:
![image](https://user-images.githubusercontent.com/92149242/162604556-06648878-0bb7-4adc-85bc-1a7a6a116b92.png)

Output:
![image](https://user-images.githubusercontent.com/92149242/162604555-fbb044ae-c1e2-49f6-915a-075562a724c8.png)

**Comment by AIisCool** [comment]
Yes used it via the following:

`python inference_realbasicvsr.py ./configs/realbasicvsr_x4.py ./checkpoints/RealBasicVSR_x4.pth ./data/test ./results/testout`

**Comment by ckkelvinchan** [comment]
Maybe this is a failure case of RealBasicVSR. Indeed, sometimes it failed on some sequences.
