### ISSUE TITLE
resources are always insufficient

### ISSUE THREAD

**Issue by little-blue** [ckkelvinchan/RealBasicVSR#44]
When training video material, the memory and video memory resources are always insufficient. Is there any parameter to solve this problem? almost 1min .mp4 25fps, 3MB, running on the 12GBRAM 12GvRam, will meet resources lack
or how should I deal with the input video before to more easily run the code

**Comment by ckkelvinchan** [comment]
Do you mean training or inference? For training, you may want to reduce the patch size and the sequence length to reduce memory consumption. For inference, you can try to separate the sequences into shorter segments. Using [max_seq_len](https://github.com/ckkelvinchan/RealBasicVSR/blob/master/inference_realbasicvsr.py#L25) may help.

**Comment by little-blue** [comment]
Thanks a lot, your answer helps me, I mean inference
