### ISSUE TITLE
about REDS dataset

### ISSUE THREAD

**Issue by sunyclj** [ckkelvinchan/RealBasicVSR#46]
Hi,i want to train X2 model,but i didn't find a way to download the REDS dataset.Do you have a link to download this dataset?thanks.

**Comment by NaiveteYaYa** [comment]
this?   
https://seungjunnah.github.io/Datasets/reds.html

**Comment by sunyclj** [comment]
@NaiveteYaYa yes,thanks.please,is Low Resolution used in the training?
![image](https://user-images.githubusercontent.com/44860428/164145475-e112637e-a67d-44a3-894e-01158fc6c786.png)

**Comment by ckkelvinchan** [comment]
> @NaiveteYaYa yes,thanks.please,is Low Resolution used in the training?
> ![image](https://user-images.githubusercontent.com/44860428/164145475-e112637e-a67d-44a3-894e-01158fc6c786.png)

No. Only high-resolution images are used to train RealBasicVSR
