### ISSUE TITLE
about training problem

### ISSUE THREAD

**Issue by Dylan-Jinx** [ckkelvinchan/RealBasicVSR#76]
Hello @ckkelvinchan , I want to retraining this model, I have a problem for about the config file UDM10 folder structure. I don't know that how to construct  this folder. is it put every folder blurx4 file to merge a folder like this is correct?

**Comment by santurini** [comment]
I was also trying to reproduce the training on the REDS dataset. How many epochs has the model been pretrained (I interpreted 300k iterations with bs 16 as around 20k epochs)? Is it normal that during the pretraining the cleaned images (after the cleaning module) have lot of blur and artifacts? Are results starting to get better only during the fine-tuning or am I missing something?

Help would really be appreciated
