### ISSUE TITLE
About cleaning mudule

### ISSUE THREAD

**Issue by JOP-Lee** [ckkelvinchan/RealBasicVSR#8]
Hi, thanks for sharing a great job. I am interested in the module about cleaning, may I ask if it's a pre-processing? could you share the code or details?  thanks a lot.

**Comment by ckkelvinchan** [comment]
Hello, thanks for your interest in our work. The cleaning module refers to the module [here](https://github.com/ckkelvinchan/RealBasicVSR/blob/master/realbasicvsr/models/backbones/real_basicvsr_net.py#L51).

**Comment by JOP-Lee** [comment]
thanks
